/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOV = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int GO = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int JUMP = 12;
  /** RegularExpression Id. */
  int WALK = 13;
  /** RegularExpression Id. */
  int LEAP = 14;
  /** RegularExpression Id. */
  int TURN = 15;
  /** RegularExpression Id. */
  int TURNTO = 16;
  /** RegularExpression Id. */
  int DROP = 17;
  /** RegularExpression Id. */
  int GET = 18;
  /** RegularExpression Id. */
  int GRAB = 19;
  /** RegularExpression Id. */
  int LETGO = 20;
  /** RegularExpression Id. */
  int NOP = 21;
  /** RegularExpression Id. */
  int BALLOONS = 22;
  /** RegularExpression Id. */
  int CHIPS = 23;
  /** RegularExpression Id. */
  int NUM = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int EAST = 26;
  /** RegularExpression Id. */
  int WEST = 27;
  /** RegularExpression Id. */
  int NORTH = 28;
  /** RegularExpression Id. */
  int SOUTH = 29;
  /** RegularExpression Id. */
  int FRONT = 30;
  /** RegularExpression Id. */
  int LEFT = 31;
  /** RegularExpression Id. */
  int BACK = 32;
  /** RegularExpression Id. */
  int AROUND = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Mov\"",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"Jump\"",
    "\"walk\"",
    "\"leap\"",
    "\"Turn\"",
    "\"TurnTo\"",
    "\"Drop\"",
    "\"Get\"",
    "\"Grab\"",
    "\"LetGo\"",
    "\"Nop\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUM>",
    "<DIGIT>",
    "\"East\"",
    "\"West\"",
    "\"North\"",
    "\"South\"",
    "\"Front\"",
    "\"Left\"",
    "\"Back\"",
    "\"Around\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
  };

}
